const refs = {
  openModalBtn: document.querySelector('[data-modal-open]'),
  closeModalBtn: document.querySelector('[data-modal-close]'),
  modal: document.querySelector('[data-modal-login]'),

  // for log-in
  headerMyLibrary: document.querySelector('#header-mylibrary'),
  headerLogIn: document.querySelector('#header-login'),
  headerLogOut: document.querySelector('#header-logout'),
  backdropLogIn: document.querySelector('.backdrop_login'),
  modalDivLogIn: document.querySelector('.modal_login'),
  formLogIn: document.querySelector('.modal_login__form'),
  formTitleSignIn: document.querySelector('.modal_login__title_signIn'),
  formTitleSignUp: document.querySelector('.modal_login__title_signUp'),
  formWrapName: document.querySelector('.modal_login__wrap_name'),
  inputPassword: document.querySelector('#password'),
  buttonShowPassword: document.querySelector('#button_show_password'),
  iconForShowPassword: document.querySelector('#icon_show_password'),
  iconForUnShowPassword: document.querySelector('#icon_un_show_password'),
  formWrapCheckbox: document.querySelector('.modal_login__wrap_checkbox'),
  formCheckbox: document.querySelector('#checkbox'),
  buttonRegister: document.querySelector('.modal_login__button_register'),
  buttonConfirm: document.querySelector('.modal_login__button_confirm'),
  signUp: document.querySelector('.signUp_now'),
  signUpLink: document.querySelector('.signUp_now__link'),
  signIn: document.querySelector('.signIn_now'),
  signInLink: document.querySelector('.signIn_now__link'),
  logOut: document.querySelector('#header-logOut'),
  // container for pagination
  pag: document.querySelector('.tui-pagination'),

  // container for markup films list
  gallery: document.querySelector('.films'),

  //search movies button on index.html page
  formSearch: document.querySelector('.search-form'),
  inputSearch: document.querySelector('.search-form__input'),
  buttonSearch: document.querySelector('.search-form__button'),
  svgSearch: document.querySelector('.search-form__icon'),
  cardLink: document.querySelector('.films list'),
  cardModal: document.querySelector('.backdrop'),

  addToWatchedBtn: document.querySelector('[data-btn="watched"]'),
  addToQueueBtn: document.querySelector('[data-btn="queue"]'),
};

export const {
  headerMyLibrary,
  headerLogIn,
  headerLogOut,
  openModalBtn,
  closeModalBtn,
  modal,
  backdropLogIn,
  modalDivLogIn,
  formLogIn,
  formTitleSignIn,
  formTitleSignUp,
  formWrapName,
  formSearch,
  inputPassword,
  inputSearch,
  svgSearch,
  buttonSearch,
  buttonShowPassword,
  iconForShowPassword,
  iconForUnShowPassword,
  formWrapCheckbox,
  formCheckbox,
  buttonRegister,
  buttonConfirm,
  signUp,
  signUpLink,
  signIn,
  signInLink,
  logOut,
  pag,
  gallery,
  cardLink,
  cardModal,
} = refs;
